import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import { Suspense } from "react";
import "@/styles/globals.css";
import { Toaster } from 'react-hot-toast';
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import LoginModal from "@/components/auth/LoginModal";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300","400", "500", "600", "700", "800", "900"], 
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Lorem Ipsum",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={montserrat.variable}>
      <body className="antialiased font-main w-full min-h-screen bg-background dark:bg-background-dark text-text dark:text-text-dark flex flex-col justify-start items-center">
        <Header />
        <main className="flex-1 w-full flex flex-col justify-start items-center mt-[70px] sm:mt-[76px]">
          {children}
        </main>
        <Footer />
        <Suspense fallback={<div />}>
          <LoginModal />
        </Suspense>
        <Toaster 
          position="top-right"
          toastOptions={{
            duration: 3000,
            style: {
              background: '#363636',
              color: '#fff',
            },
            success: {
              duration: 3000,
              iconTheme: {
                primary: '#4ade80',
                secondary: '#fff',
              },
            },
            error: {
              duration: 4000,
              iconTheme: {
                primary: '#ef4444',
                secondary: '#fff',
              },
            },
          }}
        />
      </body>
    </html>
  );
}