import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/styles/globals.css";
import Footer from "@/components/layout/Footer";
import Header from "@/components/layout/Header";
import LoginModal from "@/components/auth/LoginModal";

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "300","400", "500", "600", "700", "800", "900"], 
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Lorem Ipsum",
  description: "Generated by create next app",
  icons: {
    icon: "/images/logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={montserrat.variable}>
      <body className="antialiased font-main w-full min-h-screen bg-background dark:bg-background-dark text-text dark:text-text-dark flex flex-col justify-start items-center">
        <Header />
        <main className="flex-1 w-full max-w-[1080px] py-4 mt-[70px] sm:mt-[76px]">
          {children}
        </main>
        <Footer />
        <LoginModal />

        {/* Bg */}
        <div className='z-[-2] absolute w-full h-100 top-0 left-0 bg-second/10'></div>
      </body>
    </html>
  );
}